parserOptions:
  ecmaVersion: 2018
plugins:
  - node
  - security
  - jsdoc
  - only-ascii
extends:
  # Enforce popular JavaScript styling guide
  - airbnb-base
  # Additional rules for Node.js, lints deprecated APIs
  - plugin:node/recommended
  # Help identify potential security issues (finds a lot of false positives)
  - plugin:security/recommended
rules:
  # Disable requiring trailing commas in arrays
  comma-dangle: off
  # JSDoc rules
  jsdoc/check-param-names: 1
  jsdoc/check-tag-names: 1
  jsdoc/check-types: 1
  jsdoc/newline-after-description: 1
  jsdoc/require-param: 1
  jsdoc/require-param-name: 1
  jsdoc/require-param-type: 1
  jsdoc/require-returns-type: 1
  # Note that snippets copied from github can contain bad unicode, like the Korean space
  only-ascii/only-ascii: 1
  no-param-reassign:
    - 1
    - props: false

